# Generated by Django 5.1.6 on 2025-03-06 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "diary_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("tag", models.CharField(max_length=50)),
                ("detail", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("기쁨", "기쁨"),
                            ("슬픔", "슬픔"),
                            ("분노", "분노"),
                            ("피곤", "피곤"),
                            ("짜증", "짜증"),
                            ("무난", "무난"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
